"""
This type stub file was generated by pyright.
"""

from typing import NamedTuple, TYPE_CHECKING, Union
from uuid import UUID
from .node import Node

if TYPE_CHECKING:
    ...
class Offset(NamedTuple("NamedTuple", (("element_id", Union[UUID, Node]), ("displacement", int)))):
    """
    An Offset describes a location inside a :class:`gtirb.Node`, such as a
    :class:`gtirb.DataBlock` or :class:`gtirb.ByteInterval`.

    :ivar ~.element_id: The :class:`gtirb.Node` containing the location of
            interest.
    :ivar ~.displacement: The offset inside the Node to point to.
    """
    ...


