#!/bin/bash

# runs gtirb-pprinter via docker
# assumes command format: gtirb-pprinter INPUT_FILE [OPTIONS]... OUTPUT_FILE

if [ "$#" -lt 2 ]; then
    echo "Usage: $0 INPUT_FILE [OPTIONS]... OUTPUT_FILE"
    exit 1
fi

# Extract input and output paths
input_full_path=$(realpath "$1")
input_basedir=$(dirname "$input_full_path")
input_basename=$(basename "$input_full_path")

output_full_path=$(realpath "${@: -1}")
output_basedir=$(dirname "$output_full_path")
output_basename=$(basename "$output_full_path")

# Collect all intermediate options
options="${@:2:$(($#-2))}"

# Run the Docker command
docker run --rm -it \
    -v "$input_basedir":/input \
    -v "$output_basedir":/output \
    grammatech/ddisasm gtirb-pprinter input/"$input_basename" $options output/"$output_basename"

