"""
This type stub file was generated by pyright.
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
===- CodeBlock.proto ----------------------------------------*- Proto -*-===//

 Copyright (C) 2020 GrammaTech, Inc.

 This code is licensed under the MIT license. See the LICENSE file in the
 project root for license terms.

 This project is sponsored by the Office of Naval Research, One Liberty
 Center, 875 N. Randolph Street, Arlington, VA 22203 under contract #
 N68335-17-C-0700.  The content of the information does not necessarily
 reflect the position or policy of the Government and no official
 endorsement should be inferred.

===----------------------------------------------------------------------===//
"""
if sys.version_info >= (3, 10):
    ...
else:
    ...
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor
class _DecodeMode:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ...


class _DecodeModeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_DecodeMode.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    All_Default: _DecodeMode.ValueType
    ARM_Thumb: _DecodeMode.ValueType
    ...


class DecodeMode(_DecodeMode, metaclass=_DecodeModeEnumTypeWrapper):
    ...


All_Default: DecodeMode.ValueType
ARM_Thumb: DecodeMode.ValueType
global___DecodeMode = DecodeMode
class CodeBlock(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    UUID_FIELD_NUMBER: builtins.int
    SIZE_FIELD_NUMBER: builtins.int
    DECODE_MODE_FIELD_NUMBER: builtins.int
    uuid: builtins.bytes
    size: builtins.int
    decode_mode: global___DecodeMode.ValueType
    def __init__(self, *, uuid: builtins.bytes = ..., size: builtins.int = ..., decode_mode: global___DecodeMode.ValueType = ...) -> None:
        ...
    
    def ClearField(self, field_name: typing_extensions.Literal["decode_mode", b"decode_mode", "size", b"size", "uuid", b"uuid"]) -> None:
        ...
    


global___CodeBlock = CodeBlock
