"""
This type stub file was generated by pyright.
"""

from .abi import ABI, CallingConventionDesc
from .assembler import Assembler, AssemblerError, MultipleDefinitionsError, UndefSymbolError, UnsupportedAssemblyError
from .assembly import Constraints, Register, X86Syntax
from .intervalutils import PaddingError, join_byte_intervals, split_byte_interval
from .modify import AmbiguousCFGError, AmbiguousIRError, CFGModifiedError
from .passes import Pass, PassManager
from .patch import InsertionContext, Patch, patch_constraints
from .rewriting import RewritingContext, UnresolvableScopeError
from .scopes import AllBlocksScope, AllFunctionsScope, BlockPosition, ENTRYPOINT_NAME, FunctionPosition, MAIN_NAME, Scope, SingleBlockScope, pattern_match
from .utils import OffsetMapping, decorate_extern_symbol, show_block_asm
from .version import __version__

__all__ = ["__version__", "AmbiguousCFGError", "AmbiguousIRError", "ABI", "AllBlocksScope", "AllFunctionsScope", "Assembler", "AssemblerError", "BlockPosition", "CallingConventionDesc", "Constraints", "CFGModifiedError", "decorate_extern_symbol", "ENTRYPOINT_NAME", "FunctionPosition", "InsertionContext", "join_byte_intervals", "MAIN_NAME", "MultipleDefinitionsError", "OffsetMapping", "PaddingError", "Pass", "PassManager", "patch_constraints", "pattern_match", "Patch", "Register", "RewritingContext", "Scope", "SingleBlockScope", "show_block_asm", "split_byte_interval", "UndefSymbolError", "UnresolvableScopeError", "UnsupportedAssemblyError", "X86Syntax"]
