"""
This type stub file was generated by pyright.
"""

import gtirb
from typing import List, TYPE_CHECKING
from gtirb_rewriting.utils import OffsetMapping
from .._auxdata import CFIDirectiveType
from .assembler import Assembler

if TYPE_CHECKING:
    ...
def create_gtirb(result: Assembler.Result) -> gtirb.IR:
    """
    Creates a GTIRB IR for an assembler result. Internal implementation, do
    not call.
    """
    ...

def create_cfi_directives(result: Assembler.Result) -> OffsetMapping[List[CFIDirectiveType]]:
    """
    Creates the cfiDirectives aux data table for an assembler result.
    """
    ...

