"""
This type stub file was generated by pyright.
"""

import gtirb
import mcasm

_INDIRECT_CALL_INSTRS = ...
def is_indirect_call(isa: gtirb.Module.ISA, inst: mcasm.mc.Instruction) -> bool:
    ...

