"""
This type stub file was generated by pyright.
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
===- SymbolicExpression.proto -------------------------------*- Proto -*-===//

 Copyright (C) 2020 GrammaTech, Inc.

 This code is licensed under the MIT license. See the LICENSE file in the
 project root for license terms.

 This project is sponsored by the Office of Naval Research, One Liberty
 Center, 875 N. Randolph Street, Arlington, VA 22203 under contract #
 N68335-17-C-0700.  The content of the information does not necessarily
 reflect the position or policy of the Government and no official
 endorsement should be inferred.

===----------------------------------------------------------------------===//
"""
if sys.version_info >= (3, 10):
    ...
else:
    ...
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor
class _SymAttribute:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ...


class _SymAttributeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SymAttribute.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    GOT: _SymAttribute.ValueType
    GOTPC: _SymAttribute.ValueType
    GOTOFF: _SymAttribute.ValueType
    GOTREL: _SymAttribute.ValueType
    PLT: _SymAttribute.ValueType
    PLTOFF: _SymAttribute.ValueType
    PCREL: _SymAttribute.ValueType
    SECREL: _SymAttribute.ValueType
    TLS: _SymAttribute.ValueType
    TLSGD: _SymAttribute.ValueType
    TLSLD: _SymAttribute.ValueType
    TLSLDM: _SymAttribute.ValueType
    TLSCALL: _SymAttribute.ValueType
    TLSDESC: _SymAttribute.ValueType
    TPREL: _SymAttribute.ValueType
    TPOFF: _SymAttribute.ValueType
    DTPREL: _SymAttribute.ValueType
    DTPOFF: _SymAttribute.ValueType
    NTPOFF: _SymAttribute.ValueType
    DTPMOD: _SymAttribute.ValueType
    PAGE: _SymAttribute.ValueType
    PAGEOFF: _SymAttribute.ValueType
    CALL: _SymAttribute.ValueType
    LO: _SymAttribute.ValueType
    HI: _SymAttribute.ValueType
    HIGHER: _SymAttribute.ValueType
    HIGHEST: _SymAttribute.ValueType
    GOTNTPOFF: _SymAttribute.ValueType
    INDNTPOFF: _SymAttribute.ValueType
    G0: _SymAttribute.ValueType
    G1: _SymAttribute.ValueType
    G2: _SymAttribute.ValueType
    G3: _SymAttribute.ValueType
    UPPER16: _SymAttribute.ValueType
    LOWER16: _SymAttribute.ValueType
    LO12: _SymAttribute.ValueType
    LO15: _SymAttribute.ValueType
    LO14: _SymAttribute.ValueType
    HI12: _SymAttribute.ValueType
    HI21: _SymAttribute.ValueType
    S: _SymAttribute.ValueType
    PG: _SymAttribute.ValueType
    NC: _SymAttribute.ValueType
    ABS: _SymAttribute.ValueType
    PREL: _SymAttribute.ValueType
    PREL31: _SymAttribute.ValueType
    TARGET1: _SymAttribute.ValueType
    TARGET2: _SymAttribute.ValueType
    SBREL: _SymAttribute.ValueType
    TLSLDO: _SymAttribute.ValueType
    HI16: _SymAttribute.ValueType
    LO16: _SymAttribute.ValueType
    GPREL: _SymAttribute.ValueType
    DISP: _SymAttribute.ValueType
    OFST: _SymAttribute.ValueType
    H: _SymAttribute.ValueType
    L: _SymAttribute.ValueType
    HA: _SymAttribute.ValueType
    HIGH: _SymAttribute.ValueType
    HIGHA: _SymAttribute.ValueType
    HIGHERA: _SymAttribute.ValueType
    HIGHESTA: _SymAttribute.ValueType
    TOCBASE: _SymAttribute.ValueType
    TOC: _SymAttribute.ValueType
    NOTOC: _SymAttribute.ValueType
    ...


class SymAttribute(_SymAttribute, metaclass=_SymAttributeEnumTypeWrapper):
    """NOTE:
    We do not generalize or otherwise unify relocation attributes across
    architectures and instead prefer an explicit mapping of attributes names
    to the labels used in the assembly of each architecture.
    """
    ...


GOT: SymAttribute.ValueType
GOTPC: SymAttribute.ValueType
GOTOFF: SymAttribute.ValueType
GOTREL: SymAttribute.ValueType
PLT: SymAttribute.ValueType
PLTOFF: SymAttribute.ValueType
PCREL: SymAttribute.ValueType
SECREL: SymAttribute.ValueType
TLS: SymAttribute.ValueType
TLSGD: SymAttribute.ValueType
TLSLD: SymAttribute.ValueType
TLSLDM: SymAttribute.ValueType
TLSCALL: SymAttribute.ValueType
TLSDESC: SymAttribute.ValueType
TPREL: SymAttribute.ValueType
TPOFF: SymAttribute.ValueType
DTPREL: SymAttribute.ValueType
DTPOFF: SymAttribute.ValueType
NTPOFF: SymAttribute.ValueType
DTPMOD: SymAttribute.ValueType
PAGE: SymAttribute.ValueType
PAGEOFF: SymAttribute.ValueType
CALL: SymAttribute.ValueType
LO: SymAttribute.ValueType
HI: SymAttribute.ValueType
HIGHER: SymAttribute.ValueType
HIGHEST: SymAttribute.ValueType
GOTNTPOFF: SymAttribute.ValueType
INDNTPOFF: SymAttribute.ValueType
G0: SymAttribute.ValueType
G1: SymAttribute.ValueType
G2: SymAttribute.ValueType
G3: SymAttribute.ValueType
UPPER16: SymAttribute.ValueType
LOWER16: SymAttribute.ValueType
LO12: SymAttribute.ValueType
LO15: SymAttribute.ValueType
LO14: SymAttribute.ValueType
HI12: SymAttribute.ValueType
HI21: SymAttribute.ValueType
S: SymAttribute.ValueType
PG: SymAttribute.ValueType
NC: SymAttribute.ValueType
ABS: SymAttribute.ValueType
PREL: SymAttribute.ValueType
PREL31: SymAttribute.ValueType
TARGET1: SymAttribute.ValueType
TARGET2: SymAttribute.ValueType
SBREL: SymAttribute.ValueType
TLSLDO: SymAttribute.ValueType
HI16: SymAttribute.ValueType
LO16: SymAttribute.ValueType
GPREL: SymAttribute.ValueType
DISP: SymAttribute.ValueType
OFST: SymAttribute.ValueType
H: SymAttribute.ValueType
L: SymAttribute.ValueType
HA: SymAttribute.ValueType
HIGH: SymAttribute.ValueType
HIGHA: SymAttribute.ValueType
HIGHERA: SymAttribute.ValueType
HIGHESTA: SymAttribute.ValueType
TOCBASE: SymAttribute.ValueType
TOC: SymAttribute.ValueType
NOTOC: SymAttribute.ValueType
global___SymAttribute = SymAttribute
class SymStackConst(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    OFFSET_FIELD_NUMBER: builtins.int
    SYMBOL_UUID_FIELD_NUMBER: builtins.int
    offset: builtins.int
    symbol_uuid: builtins.bytes
    def __init__(self, *, offset: builtins.int = ..., symbol_uuid: builtins.bytes = ...) -> None:
        ...
    
    def ClearField(self, field_name: typing_extensions.Literal["offset", b"offset", "symbol_uuid", b"symbol_uuid"]) -> None:
        ...
    


global___SymStackConst = SymStackConst
class SymAddrConst(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    OFFSET_FIELD_NUMBER: builtins.int
    SYMBOL_UUID_FIELD_NUMBER: builtins.int
    offset: builtins.int
    symbol_uuid: builtins.bytes
    def __init__(self, *, offset: builtins.int = ..., symbol_uuid: builtins.bytes = ...) -> None:
        ...
    
    def ClearField(self, field_name: typing_extensions.Literal["offset", b"offset", "symbol_uuid", b"symbol_uuid"]) -> None:
        ...
    


global___SymAddrConst = SymAddrConst
class SymAddrAddr(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SCALE_FIELD_NUMBER: builtins.int
    OFFSET_FIELD_NUMBER: builtins.int
    SYMBOL1_UUID_FIELD_NUMBER: builtins.int
    SYMBOL2_UUID_FIELD_NUMBER: builtins.int
    scale: builtins.int
    offset: builtins.int
    symbol1_uuid: builtins.bytes
    symbol2_uuid: builtins.bytes
    def __init__(self, *, scale: builtins.int = ..., offset: builtins.int = ..., symbol1_uuid: builtins.bytes = ..., symbol2_uuid: builtins.bytes = ...) -> None:
        ...
    
    def ClearField(self, field_name: typing_extensions.Literal["offset", b"offset", "scale", b"scale", "symbol1_uuid", b"symbol1_uuid", "symbol2_uuid", b"symbol2_uuid"]) -> None:
        ...
    


global___SymAddrAddr = SymAddrAddr
class SymbolicExpression(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ADDR_CONST_FIELD_NUMBER: builtins.int
    ADDR_ADDR_FIELD_NUMBER: builtins.int
    ATTRIBUTE_FLAGS_FIELD_NUMBER: builtins.int
    @property
    def addr_const(self) -> global___SymAddrConst:
        ...
    
    @property
    def addr_addr(self) -> global___SymAddrAddr:
        ...
    
    @property
    def attribute_flags(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___SymAttribute.ValueType]:
        ...
    
    def __init__(self, *, addr_const: global___SymAddrConst | None = ..., addr_addr: global___SymAddrAddr | None = ..., attribute_flags: collections.abc.Iterable[global___SymAttribute.ValueType] | None = ...) -> None:
        ...
    
    def HasField(self, field_name: typing_extensions.Literal["addr_addr", b"addr_addr", "addr_const", b"addr_const", "value", b"value"]) -> builtins.bool:
        ...
    
    def ClearField(self, field_name: typing_extensions.Literal["addr_addr", b"addr_addr", "addr_const", b"addr_const", "attribute_flags", b"attribute_flags", "value", b"value"]) -> None:
        ...
    
    def WhichOneof(self, oneof_group: typing_extensions.Literal["value", b"value"]) -> typing_extensions.Literal["addr_const", "addr_addr"] | None:
        ...
    


global___SymbolicExpression = SymbolicExpression
